name: Docker Testing

on:
  push:
    branches:
      - master

jobs:
  my_job:
    runs-on: ubuntu-latest
    container: node:10.16-jessie

    steps:
      - name: die
        run: echo "die world"
